### PR TITLE
Artykuł o hackathonach

### PR DESCRIPTION
**Pull request by Szczepaniak-M**

### CODE REVIEW

**Comment by rrudol** [comment]
@Gumkle 
I'd suggest using squash merge for blog post PRs 😉 
image

**Review by rrudol — APPROVED** [review]
In the article, you are using the word `hackaton`, but in title, I can see `hackathon`.
Would it be nice to add some photos, maybe from previous AKAI events?
How about adding some incoming online hackathons and/or linking our [Hackathons Collector](https://hackathons.akai.org.pl/) page (but then we should update hackathons there)

Either way, it is a good article - informative and inspiring - approve from me 👏

**Comment by rrudol** [comment]
BTW. @Szczepaniak-M have you seen this commercial? 😄 

[Jetbrains Hackathon Commercial](https://www.youtube.com/watch?v=rhAunB7UQFQ)

**Comment by Szczepaniak-M** [comment]
I will close this PR and after the fix, I will make another one

**Pull request closed without merging**
